### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by matt-dees** [netplier-tool/NetPlier#2]
Hi all,

This is awesome work! I was wondering what the licensing terms are for this, as I would like to make some changes of my own to support more protocols. 

For reference, here are some commonly used licenses: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

Thanks, and congratulations on the fantastic work.

**Comment by yapengye** [comment]
Hi @matt-dees , thanks for your interest. The license has been updated.
