### ISSUE TITLE
Question about tmp_results/msa_fields_visual.txt

### ISSUE THREAD

**Issue by jaredchandler** [netplier-tool/NetPlier#3]
Hello,

I have a question on interpreting the output of NetPlier and determining the final field boundaries inferred.

Considering the first few lines of https://github.com/netplier-tool/NetPlier/blob/master/tmp_results/dhcp/msa_fields_visual.txt

````
01 010600 4e b9 5f c5 00 00 00 00 ac 14 02 10 00 00 00 00 -- -- -- -- 00 00 00 00 0000000000 0c 29 
02 010600 4e b9 5f c5 00 00 00 00 -- -- -- -- 00 00 00 00 ac 14 02 10 00 00 00 00 0000000000 0c 29 
01 010600 b3 a9 b4 25 00 00 00 00 ac 12 02 10 00 00 00 00 -- -- -- -- 00 00 00 00 0000000000 0c 29 
02 010600 b3 a9 b4 25 00 00 00 00 -- -- -- -- 00 00 00 00 ac 12 02 10 00 00 00 00 0000000000 0c 29 
01 010600 f7 ba dc d9 00 00 00 00 ac 14 02 15 00 00 00 00 -- -- -- -- 00 00 00 00 0000000000 0c 29 
02 010600 f7 ba dc d9 00 00 00 00 ac 14 02 15 00 00 00 00 -- -- -- -- 00 00 00 00 0000000000 0c 29 
````

Does this mean the first field in each message is 1-byte width, followed by a field 3 bytes in width?

What does ----- mean for the message? Does it mean that a field in other message was not present in this message?

Thank you for helping clarify :)

**Comment by yapengye** [comment]
Hi @jaredchandler ,

> Does this mean the first field in each message is 1-byte width, followed by a field 3 bytes in width?

Yes.

> What does ----- mean for the message? Does it mean that a field in other message was not present in this message?

'-' is the inserted gap for alignment. 
This file shows the results for keyword candidates instead of all fields. After the keyword inference and clustering, we could run MSA of messages in each message type again (usually with fewer gaps). In that case, '-' may denote fields with variable length or fields that are not present.

**Comment by jaredchandler** [comment]
Thanks!
